name: Deploy
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'master'
      name:
        description: 'name to deploy'
        required: true
        default: 'master'
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}
      
      - run: rm -rf .git
      - run: git init
      - run: git add -A
      - run: git commit -m "initial commit"
      - run: cat src/App.js

      - name: Dokku
        uses: dokku/github-action@v1.0.1
        with:
          branch: ${{ github.event.inputs.branch }}
          git_remote_url: 'ssh://dokku@dokku.devsters.de:22/${{ github.event.inputs.name }}'
          ssh_private_key: ${{ secrets.SSHKEY }}
