name: Deploy
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'master'
      name:
        description: 'name to deploy'
        required: true
        default: 'master'
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSHKEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - run: |
          git remote add dokku dokku@dokku.devsters.de:${{ github.event.inputs.name }}
          git checkout ${{ github.event.inputs.branch }}
          git push dokku HEAD:master
