name: Delete Approval App

on:
  workflow_dispatch:
    inputs:
      appname:
        description: 'Approval App Name to Destroy'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  delete-dokku-app:
    runs-on: self-hosted
    steps:
      - run: sudo dokku apps:destroy --force ${{ github.event.inputs.appname }}
