name: Deploy
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'master'
      name:
        description: 'name to deploy'
        required: true
        default: 'master'
jobs:
  # This workflow contains a single job called "build"
  deploy-to-dokku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - run: echo "commit_sha=$(git rev-parse HEAD 2>/dev/null)" >> $GITHUB_ENV

      - name: Dokku
        uses: dokku/github-action@v1.0.1
        with:
          git_remote_url: 'ssh://dokku@dokku.devsters.de:22/${{ github.event.inputs.name }}'
          ssh_private_key: ${{ secrets.SSHKEY }}
          ci_commit: ${{ env.commit_sha }}
